### ISSUE TITLE
Help plz

### ISSUE THREAD

**Issue by ereimer69** [NotNanook/Ascendit-Launcher#1]
Hey dude, I'm kinda amateur at this stuff so could you help me through this a lil? Whenever i run your launcher, the version is outdated which is probably my fault, and the cheats don't load. I have my directory set for where my raot.exe file is with the new raot launcher but idk if that screws with ascendit launcher. I guess what im looking for is a tutorial on how to work the launcher. thx in advance

**Comment by NotNanook** [comment]
I know its a pretty late answer but im currently working on a auto-update version of the launcher that wont have these problems. I will release asap. In the meantime you can manually download ascendit-raot and use that
