### ISSUE TITLE
Launcher and Raot game

### ISSUE THREAD

**Issue by Shivlyakov** [NotNanook/Ascendit-Launcher#2]
hello, I'm new using github so I'm sorry for asking questions in the wrong places, well I found your topic today and I downloaded acendit launcher and ascendit raot, but I can't open the launcher, I don't find any executables or something like that, could help me?

**Comment by NotNanook** [comment]
There you go. You found it. The reason why i wanted you to open an issue is that other people can find it as well. Youll have to explain what exactly is not working. If you have downloaded the launcher from this github page under releases everything should work

**Comment by Shivlyakov** [comment]
actually I'm not finding the launcher executable. 
![image](https://user-images.githubusercontent.com/124396587/216703425-db8625ae-8fcf-4177-a1f9-53f932552f6d.png)

**Comment by NotNanook** [comment]
Well yeah, because you downloaded the source code. Under releases you'll find an .MSI installer

**Comment by Shivlyakov** [comment]
ohh okay, where is the releases folder

**Comment by Shivlyakov** [comment]
What should I do now?
![image](https://user-images.githubusercontent.com/124396587/216711095-510301f8-716d-4027-a3a4-60bf5cc19d8f.png)

**Comment by NotNanook** [comment]
You don't have to start raot yourself. Just press play and that's it. Open GUI with right shift

**Comment by Shivlyakov** [comment]
I'm pressing play on the ascendit launcher but nothing happens, I can't inject it, I already installed it in the same folder (roaming) but nothing happens

**Comment by NotNanook** [comment]
Close raot. Open launcher. Press play. Press rshift after when joining a game

**Comment by Shivlyakov** [comment]
the game does not open when I press play in the launcher

**Comment by NotNanook** [comment]
Does the launcher crash?

**Comment by Shivlyakov** [comment]
look i made a video
https://gofile.io/d/SeYMYV

**Comment by Shivlyakov** [comment]
![d](https://user-images.githubusercontent.com/124396587/216719278-2b760b75-b215-42d6-a914-f706f87b3d8b.png)
raot path

**Comment by NotNanook** [comment]
If the raot.exe is in that folder, replace the path in the config file with your path. Otherwise the launcher won't know where your raot.exe is located

**Comment by Shivlyakov** [comment]
is correct?
![f](https://user-images.githubusercontent.com/124396587/216720090-674001dd-a64a-411c-bcb6-ab502b6558c0.png)

**Comment by NotNanook** [comment]
I see the problem, the config file you gotta change is in appdata

**Comment by Shivlyakov** [comment]
the ascendit launcher folder contains a Data folder but it is empty
![a](https://user-images.githubusercontent.com/124396587/216726513-8d9cdcde-7a8e-4b2d-be17-6996e11c37fd.png)

**Comment by NotNanook** [comment]
ok that is very weird. ill check if i find anything in the code

**Comment by Shivlyakov** [comment]
ohh don't worry, I'll be waiting :D
so as not to be in doubt I made another video
https://gofile.io/d/1Hbr0x
:)
